name: Schwi Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  schwi-build:
    name: Schwi Backend Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup musl-tools
        run: sudo apt-get install musl-tools
        
      - name: Build Go Code
        run: CGO_ENABLED=1 CC=musl-gcc go build --ldflags '-linkmode external -extldflags "-static"' main.go
       
      - name: Archieve Artifacts
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: main
          path: main
